### ISSUE TITLE
Text gets blurry after recompress

### ISSUE THREAD

**Issue by steveh80** [danielgtaylor/jpeg-archive#12]
Hi there, 

first of all, thanks for that great work. We're considering jpeg-recompress to use in production, but we experience strange behavior when we have text in that image.

I've tried all different compression methods, but text gets blurry with all of them. See attached images. I even tried to use best quality and accurate settings:

`jpeg-recompress --accurate --quality veryhigh --min 100 image.jpg image_recompress.jpg`

You have any ideas what to do to to get this text sharp? (Adept.sh and jpeg-mini gets it sharp anyway)

Image before recompress:
![skyscraper_xenofit_v4](https://cloud.githubusercontent.com/assets/2198342/4524169/bc4db446-4d40-11e4-98f4-9110682ad71d.jpg)

After recompress:
![skyscraper_xenofit_v4_recompress](https://cloud.githubusercontent.com/assets/2198342/4524170/bc539a32-4d40-11e4-9939-ce3bceeb42e7.jpg)

**Comment by Biozynotiker** [comment]
The text gets blurry, because jpeg-recompress allways produce jpeg's with chroma-subsampling.
All jpeg are saved with chroma-subsampling 2x2 (4:2:0). As far as i know, jpeg-recompress uses moz-jpeg source to create jpreg's, and moz-jpeg uses 2x2 as default.

It' would be nice, the next version has an option to keep the original sampling method (1x1,2x1,1x2) or compress all to 2x2.

And btw, thanks for jpeg-recompress.

**Comment by danielgtaylor** [comment]
I've gone ahead and added a method to set 4:4:4 sampling and it produces the correct image, but it compresses to 86% of the original size instead of 78%, so realize that this option may not be desired in the general case.

**Comment by danielgtaylor** [comment]
This fix is now released in version 2.1.0.
