### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by szepeviktor** [danielgtaylor/jpeg-archive#90]
Are there plans to release the next version of jpeg-archive?

**Comment by adityapatadia** [comment]
Lot of commits since last release. We would appreciate a release.

**Comment by alanorth** [comment]
I don't mind compiling from source, but some GNU/Linux distributions can't/won't package new versions unless there are tagged releases. Arch Linux currently packages version 2.1.1, for example, and says there [must be "a newer stable release" in order to flag a package as out of date](https://www.archlinux.org/packages/community/x86_64/jpeg-archive/flag/).

**Comment by szepeviktor** [comment]
Related https://github.com/danielgtaylor/jpeg-archive/issues/83
